# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

global:
  scrape_interval: 30s
  evaluation_interval: 30s

  external_labels:
    environment: azure
    instance: 10.1.39.68
    stack: opentelemetry-demo

otlp:
  keep_identifying_resource_attributes: true

  promote_resource_attributes:
    - service.instance.id
    - service.name
    - service.namespace
    - service.version
    - service.criticality
    - cloud.availability_zone
    - cloud.region
    - deployment.environment.name
    - container.name
    - host.name
    - postgresql.database.name
    - postgresql.schema.name
    - postgresql.table.name
    - postgresql.index.name
    - kafka.cluster.alias
    - collector.instance.id

storage:
  tsdb:
    out_of_order_time_window: 30m
